ALTER TABLE `order_log` ADD `status` ENUM( 'ACTIVE', 'FILLED', 'CANCELLED_USER', 'OUT_OF_FUNDS','REPLACED') NOT NULL;
ALTER TABLE `order_log` ADD `btc_remaining` DOUBLE( 16, 8 ) UNSIGNED NOT NULL ;
ALTER TABLE `transactions` ADD INDEX ( `log_id1` ) ;
ALTER TABLE `transactions` ADD INDEX ( `log_id` ) ;
ALTER TABLE `orders` ADD INDEX ( `log_id` ) ;
ALTER TABLE `api_keys` CHANGE `nonce` `nonce` BIGINT( 20 ) UNSIGNED NOT NULL;
ALTER TABLE `api_keys` ADD INDEX ( `nonce` ) ;
ALTER TABLE `site_users`
  DROP `api_key`,
  DROP `api_secret`;

INSERT INTO `admin_controls_methods` (`id`, `method`, `arguments`, `order`, `control_id`, `p_id`) VALUES
(2281, 'textInput', 'a:13:{s:4:"name";s:6:"status";s:7:"caption";s:6:"Status";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:4:"enum";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 5, 252, 0),
(2282, 'hiddenInput', 'a:8:{s:4:"name";s:13:"btc_remaining";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:7:"jscript";s:0:"";s:20:"is_current_timestamp";s:0:"";s:15:"on_every_update";s:0:"";}', 1, 252, 0),
(2283, 'field', 'a:14:{s:4:"name";s:6:"status";s:7:"caption";s:6:"Status";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 4, 253, 0),
(2284, 'field', 'a:18:{s:4:"name";s:6:"status";s:8:"subtable";s:0:"";s:14:"header_caption";s:6:"Status";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}', 5, 254, 0);

DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2264;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2265;

CREATE TABLE IF NOT EXISTS `bitcoind_log` (
  `transaction_id` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `bitcoind_log` ADD `id` INT( 10 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE `bitcoind_log` ADD `amount` DOUBLE( 16, 8 ) UNSIGNED NOT NULL;
ALTER TABLE `bitcoind_log` ADD `date` DATETIME NOT NULL;

INSERT INTO `admin_controls_methods` (`id`, `method`, `arguments`, `order`, `control_id`, `p_id`) VALUES
(2285, 'field', 'a:18:{s:4:"name";s:15:"verified_google";s:8:"subtable";s:0:"";s:14:"header_caption";s:11:"Google 2FA?";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}', 8, 132, 0);

INSERT INTO `admin_controls_methods` (`id`, `method`, `arguments`, `order`, `control_id`, `p_id`) VALUES (2279, 'field', 'a:18:{s:4:"name";s:5:"email";s:8:"subtable";s:0:"";s:14:"header_caption";s:5:"Email";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}', 6, 132, 0);

ALTER TABLE status ADD `chf_escrow` DOUBLE( 10, 2 ) NOT NULL;
ALTER TABLE status ADD `aud_escrow` DOUBLE( 10, 2 ) NOT NULL;

INSERT INTO `admin_controls_methods` (`id`, `method`, `arguments`, `order`, `control_id`, `p_id`) VALUES
(2286, 'textInput', 'a:13:{s:4:"name";s:10:"chf_escrow";s:7:"caption";s:3:"CHF";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 17, 244, 0),
(2287, 'textInput', 'a:13:{s:4:"name";s:10:"aud_escrow";s:7:"caption";s:3:"AUD";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 18, 244, 0);

ALTER TABLE conversions ADD `total_withdrawals` DOUBLE( 12, 2 ) NOT NULL;
ALTER TABLE conversions ADD `profit_to_factor` DOUBLE( 12, 2 ) NOT NULL;
ALTER TABLE conversions ADD `factored` ENUM('Y','N') NOT NULL DEFAULT 'N';

INSERT INTO `admin_controls_methods` (`id`, `method`, `arguments`, `order`, `control_id`, `p_id`) VALUES
(2288, 'textInput', 'a:13:{s:4:"name";s:17:"total_withdrawals";s:7:"caption";s:17:"Total Withdrawals";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 5, 266, 0),
(2289, 'aggregate', 'a:5:{s:4:"name";s:27:"balance_after_consolidation";s:7:"formula";s:31:"[amount] - [total_withdrawals]";s:7:"caption";s:28:"Balance After Consol. (Ref.)";s:8:"link_url";s:0:"";s:10:"run_in_sql";s:0:"";}', 6, 266, 0),
(2290, 'textInput', 'a:13:{s:4:"name";s:16:"profit_to_factor";s:7:"caption";s:16:"Profit to Factor";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 7, 266, 0),
(2291, 'hiddenInput', 'a:8:{s:4:"name";s:8:"factored";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:4:"enum";s:7:"jscript";s:0:"";s:20:"is_current_timestamp";s:0:"";s:15:"on_every_update";s:0:"";}', 0, 266, 0),
(2292, 'field', 'a:18:{s:4:"name";s:17:"total_withdrawals";s:8:"subtable";s:0:"";s:14:"header_caption";s:15:"Total Withdraw.";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}', 6, 267, 0),
(2293, 'dateWidget', 'a:19:{s:4:"name";s:5:"date1";s:7:"caption";s:8:"End Date";s:8:"required";s:0:"";s:4:"time";s:0:"";s:4:"ampm";s:0:"";s:9:"req_start";s:0:"";s:7:"req_end";s:0:"";s:5:"value";s:0:"";s:7:"link_to";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";s:6:"format";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:19:"is_filter_range_end";s:0:"";s:14:"document_ready";s:0:"";s:9:"only_time";s:0:"";s:16:"regular_interval";s:0:"";s:13:"only_interval";s:0:"";}', 2, 266, 0),
(2294, 'field', 'a:18:{s:4:"name";s:5:"date1";s:8:"subtable";s:0:"";s:14:"header_caption";s:8:"End Date";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}', 3, 267, 0),
(2295, 'field', 'a:18:{s:4:"name";s:16:"profit_to_factor";s:8:"subtable";s:0:"";s:14:"header_caption";s:16:"Profit to Factor";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}', 8, 267, 0),
(2296, 'field', 'a:18:{s:4:"name";s:8:"factored";s:8:"subtable";s:0:"";s:14:"header_caption";s:19:"Factored by System?";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}', 9, 267, 0);


UPDATE `admin_controls_methods` SET `id` = 2201,`method` = 'textInput',`arguments` = 'a:13:{s:4:"name";s:6:"amount";s:7:"caption";s:7:"Balance";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}',`order` = 4,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2201;
UPDATE `admin_controls_methods` SET `id` = 2202,`method` = 'selectInput',`arguments` = 'a:20:{s:4:"name";s:8:"currency";s:7:"caption";s:8:"Currency";s:8:"required";s:0:"";s:5:"value";s:0:"";s:13:"options_array";s:0:"";s:8:"subtable";s:10:"currencies";s:15:"subtable_fields";a:1:{s:8:"currency";s:8:"currency";}s:13:"subtable_f_id";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:10:"f_id_field";s:0:"";s:12:"default_text";s:0:"";s:10:"depends_on";s:0:"";s:20:"function_to_elements";s:0:"";s:16:"first_is_default";s:0:"";s:5:"level";s:0:"";s:11:"concat_char";s:0:"";s:9:"is_catsel";s:0:"";}',`order` = 3,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2202;
UPDATE `admin_controls_methods` SET `id` = 2207,`method` = 'dateWidget',`arguments` = 'a:19:{s:4:"name";s:4:"date";s:7:"caption";s:10:"Start Date";s:8:"required";s:0:"";s:4:"time";s:0:"";s:4:"ampm";s:0:"";s:9:"req_start";s:0:"";s:7:"req_end";s:0:"";s:5:"value";s:0:"";s:7:"link_to";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";s:6:"format";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:19:"is_filter_range_end";s:0:"";s:14:"document_ready";s:0:"";s:9:"only_time";s:0:"";s:16:"regular_interval";s:0:"";s:13:"only_interval";s:0:"";}',`order` = 1,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2207;
UPDATE `admin_controls_methods` SET `id` = 2205,`method` = 'submitButton',`arguments` = 'a:6:{s:4:"name";s:4:"Save";s:5:"value";s:4:"Save";s:2:"id";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";}',`order` = 9,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2205;
UPDATE `admin_controls_methods` SET `id` = 2206,`method` = 'cancelButton',`arguments` = 'a:4:{s:5:"value";s:6:"Cancel";s:2:"id";s:0:"";s:5:"class";s:0:"";s:5:"style";s:0:"";}',`order` = 10,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2206;
UPDATE `admin_controls_methods` SET `id` = 2213,`method` = 'checkBox',`arguments` = 'a:9:{s:4:"name";s:9:"is_active";s:7:"caption";s:14:"Factor Profit?";s:8:"required";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:11:"label_class";s:0:"";s:7:"checked";s:0:"";}',`order` = 8,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2213;
UPDATE `admin_controls_methods` SET `id` = 2288,`method` = 'textInput',`arguments` = 'a:13:{s:4:"name";s:17:"total_withdrawals";s:7:"caption";s:17:"Total Withdrawals";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}',`order` = 5,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2288;
UPDATE `admin_controls_methods` SET `id` = 2289,`method` = 'aggregate',`arguments` = 'a:5:{s:4:"name";s:27:"balance_after_consolidation";s:7:"formula";s:31:"[amount] - [total_withdrawals]";s:7:"caption";s:28:"Balance After Consol. (Ref.)";s:8:"link_url";s:0:"";s:10:"run_in_sql";s:0:"";}',`order` = 6,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2289;
UPDATE `admin_controls_methods` SET `id` = 2290,`method` = 'textInput',`arguments` = 'a:13:{s:4:"name";s:16:"profit_to_factor";s:7:"caption";s:16:"Profit to Factor";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}',`order` = 7,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2290;
UPDATE `admin_controls_methods` SET `id` = 2291,`method` = 'hiddenInput',`arguments` = 'a:8:{s:4:"name";s:8:"factored";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:4:"enum";s:7:"jscript";s:0:"";s:20:"is_current_timestamp";s:0:"";s:15:"on_every_update";s:0:"";}',`order` = 0,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2291;
UPDATE `admin_controls_methods` SET `id` = 2293,`method` = 'dateWidget',`arguments` = 'a:19:{s:4:"name";s:5:"date1";s:7:"caption";s:8:"End Date";s:8:"required";s:0:"";s:4:"time";s:0:"";s:4:"ampm";s:0:"";s:9:"req_start";s:0:"";s:7:"req_end";s:0:"";s:5:"value";s:0:"";s:7:"link_to";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";s:6:"format";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:19:"is_filter_range_end";s:0:"";s:14:"document_ready";s:0:"";s:9:"only_time";s:0:"";s:16:"regular_interval";s:0:"";s:13:"only_interval";s:0:"";}',`order` = 2,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2293;
UPDATE `admin_controls_methods` SET `id` = 2208,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:4:"date";s:8:"subtable";s:0:"";s:14:"header_caption";s:10:"Start Date";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 2,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2208;
UPDATE `admin_controls_methods` SET `id` = 2209,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:6:"amount";s:8:"subtable";s:0:"";s:14:"header_caption";s:7:"Balance";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 5,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2209;
UPDATE `admin_controls_methods` SET `id` = 2210,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:8:"currency";s:8:"subtable";s:10:"currencies";s:14:"header_caption";s:8:"Currency";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";a:1:{s:8:"currency";s:8:"currency";}s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 4,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2210;
UPDATE `admin_controls_methods` SET `id` = 2214,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:9:"is_active";s:8:"subtable";s:0:"";s:14:"header_caption";s:14:"Factor Profit?";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 7,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2214;
UPDATE `admin_controls_methods` SET `id` = 2215,`method` = 'filterDateStart',`arguments` = 'a:9:{s:10:"field_name";s:16:"conversions.date";s:7:"caption";s:10:"Start Date";s:5:"value";s:0:"";s:4:"time";s:0:"";s:4:"ampm";s:0:"";s:9:"req_start";s:0:"";s:7:"req_end";s:0:"";s:7:"link_to";s:0:"";s:6:"format";s:0:"";}',`order` = 0,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2215;
UPDATE `admin_controls_methods` SET `id` = 2292,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:17:"total_withdrawals";s:8:"subtable";s:0:"";s:14:"header_caption";s:15:"Total Withdraw.";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 6,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2292;
UPDATE `admin_controls_methods` SET `id` = 2294,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:5:"date1";s:8:"subtable";s:0:"";s:14:"header_caption";s:8:"End Date";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 3,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2294;
UPDATE `admin_controls_methods` SET `id` = 2295,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:16:"profit_to_factor";s:8:"subtable";s:0:"";s:14:"header_caption";s:16:"Profit to Factor";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 8,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2295;
UPDATE `admin_controls_methods` SET `id` = 2296,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:8:"factored";s:8:"subtable";s:0:"";s:14:"header_caption";s:19:"Factored by System?";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 9,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2296;


