INSERT INTO `currencies` (`id`, `currency`, `fa_symbol`, `account_number`, `account_name`, `is_active`, `usd_bid`, `usd_ask`) VALUES
(39, 'AUD', 'A$', 0, '', 'Y', '0.8867', '0.8877'),
(40, 'CHF', 'CHF', 0, '', 'Y', '1.0579', '1.0579');

ALTER TABLE `site_users` ADD `aud` DOUBLE( 10, 2 ) NOT NULL AFTER `jpy` ,
ADD `chf` DOUBLE( 10, 2 ) NOT NULL AFTER `aud`;

INSERT INTO `admin_controls_methods` (`id`, `method`, `arguments`, `order`, `control_id`, `p_id`) VALUES
(2272, 'textInput', 'a:13:{s:4:"name";s:3:"aud";s:7:"caption";s:11:"AUD Balance";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 42, 130, 0),
(2273, 'textInput', 'a:13:{s:4:"name";s:3:"chf";s:7:"caption";s:11:"CHF Balance";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}', 43, 130, 0),
(2274, 'field', 'a:14:{s:4:"name";s:3:"aud";s:7:"caption";s:11:"AUD Balance";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 16, 131, 0),
(2275, 'field', 'a:14:{s:4:"name";s:3:"chf";s:7:"caption";s:11:"CHF Balance";s:8:"subtable";s:0:"";s:15:"subtable_fields";s:0:"";s:8:"link_url";s:0:"";s:11:"concat_char";s:0:"";s:7:"in_form";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:14:"override_value";s:0:"";s:13:"link_id_field";s:0:"";}', 16, 131, 0);

ALTER TABLE `transactions` ADD `factored` ENUM( 'Y', 'N' ) NOT NULL DEFAULT 'N';
ALTER TABLE `transactions` ADD INDEX ( `factored` ) ;
ALTER TABLE conversions DROP conversions.currency1;
ALTER TABLE conversions DROP conversions.amount_received;
ALTER TABLE conversions DROP conversions.amount_needed;
ALTER TABLE conversions DROP conversions.factored;
ALTER TABLE conversions DROP conversions.factored1;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2227;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2211;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2218;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2226;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2204;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2225;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2217;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2254;
DELETE FROM `admin_controls_methods` WHERE `admin_controls_methods`.`id` = 2276;
UPDATE `admin_controls_methods` SET `id` = 2208,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:4:"date";s:8:"subtable";s:0:"";s:14:"header_caption";s:4:"Date";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 2,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2208;
UPDATE `admin_controls_methods` SET `id` = 2209,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:6:"amount";s:8:"subtable";s:0:"";s:14:"header_caption";s:7:"Balance";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 4,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2209;
UPDATE `admin_controls_methods` SET `id` = 2210,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:8:"currency";s:8:"subtable";s:10:"currencies";s:14:"header_caption";s:8:"Currency";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";a:1:{s:8:"currency";s:8:"currency";}s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 3,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2210;
UPDATE `admin_controls_methods` SET `id` = 2214,`method` = 'field',`arguments` = 'a:18:{s:4:"name";s:9:"is_active";s:8:"subtable";s:0:"";s:14:"header_caption";s:4:"Done";s:6:"filter";s:1:"Y";s:8:"link_url";s:0:"";s:15:"subtable_fields";s:0:"";s:22:"subtable_fields_concat";s:0:"";s:5:"class";s:0:"";s:18:"aggregate_function";s:0:"";s:12:"thumb_amount";s:0:"";s:12:"media_amount";s:0:"";s:10:"media_size";s:0:"";s:10:"f_id_field";s:0:"";s:8:"order_by";s:0:"";s:9:"order_asc";s:0:"";s:11:"link_is_tab";s:0:"";s:16:"limit_is_curdate";s:0:"";s:8:"is_media";s:0:"";}',`order` = 5,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2214;
UPDATE `admin_controls_methods` SET `id` = 2215,`method` = 'filterDateStart',`arguments` = 'a:9:{s:10:"field_name";s:16:"conversions.date";s:7:"caption";s:10:"Start Date";s:5:"value";s:0:"";s:4:"time";s:0:"";s:4:"ampm";s:0:"";s:9:"req_start";s:0:"";s:7:"req_end";s:0:"";s:7:"link_to";s:0:"";s:6:"format";s:0:"";}',`order` = 0,`control_id` = 267,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2215;
UPDATE `admin_controls_methods` SET `id` = 2201,`method` = 'textInput',`arguments` = 'a:13:{s:4:"name";s:6:"amount";s:7:"caption";s:7:"Balance";s:8:"required";s:0:"";s:5:"value";s:0:"";s:2:"id";s:0:"";s:13:"db_field_type";s:7:"decimal";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:15:"is_manual_array";s:0:"";s:9:"is_unique";s:0:"";s:12:"default_text";s:0:"";s:17:"delete_whitespace";s:0:"";}',`order` = 2,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2201;
UPDATE `admin_controls_methods` SET `id` = 2202,`method` = 'selectInput',`arguments` = 'a:20:{s:4:"name";s:8:"currency";s:7:"caption";s:8:"Currency";s:8:"required";s:0:"";s:5:"value";s:0:"";s:13:"options_array";s:0:"";s:8:"subtable";s:10:"currencies";s:15:"subtable_fields";a:1:{s:8:"currency";s:8:"currency";}s:13:"subtable_f_id";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:10:"f_id_field";s:0:"";s:12:"default_text";s:0:"";s:10:"depends_on";s:0:"";s:20:"function_to_elements";s:0:"";s:16:"first_is_default";s:0:"";s:5:"level";s:0:"";s:11:"concat_char";s:0:"";s:9:"is_catsel";s:0:"";}',`order` = 1,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2202;
UPDATE `admin_controls_methods` SET `id` = 2207,`method` = 'dateWidget',`arguments` = 'a:19:{s:4:"name";s:4:"date";s:7:"caption";s:4:"Date";s:8:"required";s:0:"";s:4:"time";s:1:"1";s:4:"ampm";s:1:"1";s:9:"req_start";s:0:"";s:7:"req_end";s:0:"";s:5:"value";s:0:"";s:7:"link_to";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";s:6:"format";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:19:"is_filter_range_end";s:0:"";s:14:"document_ready";s:0:"";s:9:"only_time";s:0:"";s:16:"regular_interval";s:0:"";s:13:"only_interval";s:0:"";}',`order` = 0,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2207;
UPDATE `admin_controls_methods` SET `id` = 2205,`method` = 'submitButton',`arguments` = 'a:6:{s:4:"name";s:4:"Save";s:5:"value";s:4:"Save";s:2:"id";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";}',`order` = 4,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2205;
UPDATE `admin_controls_methods` SET `id` = 2206,`method` = 'cancelButton',`arguments` = 'a:4:{s:5:"value";s:6:"Cancel";s:2:"id";s:0:"";s:5:"class";s:0:"";s:5:"style";s:0:"";}',`order` = 5,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2206;
UPDATE `admin_controls_methods` SET `id` = 2213,`method` = 'checkBox',`arguments` = 'a:9:{s:4:"name";s:9:"is_active";s:7:"caption";s:5:"Done?";s:8:"required";s:0:"";s:2:"id";s:0:"";s:5:"class";s:0:"";s:7:"jscript";s:0:"";s:5:"style";s:0:"";s:11:"label_class";s:0:"";s:7:"checked";s:0:"";}',`order` = 3,`control_id` = 266,`p_id` = 0 WHERE `admin_controls_methods`.`id` = 2213;


