<?php
include 'cfg.php';

$header = new Header();
$header->metaAuthor();
$header->metaDesc();
$header->metaKeywords();
$header->cssFile('../shared2/css/colorpicker.css');
$header->cssFile('../shared2/css/reset.css');
$header->cssFile('css/'.$CFG->skin.'/default.css','all');
$header->cssFile('css/'.$CFG->skin.'/default_ie6.css','all','IE 6');
$header->cssFile('css/'.$CFG->skin.'/default_ie7.css','all','IE 7');
$header->cssFile('css/'.$CFG->skin.'/default_ie8.css','all','IE 8');
$header->jsFile('../shared2/js/jquery-1.4.2.min.js');
$header->jsFile('../shared2/js/jquery-ui-1.8.5.custom.min.js');
$header->jsFile('../shared2/js/ajax.js');
$header->jsFile('../shared2/js/calendar.js');
$header->jsFile('../shared2/js/colorpicker.js');
$header->jsFile('../shared2/js/comments.js');
$header->jsFile('../shared2/js/form.js');
$header->jsFile('../shared2/js/file_manager.js');
$header->jsFile('../shared2/js/flow_chart.js');
$header->jsFile('../shared2/js/gallery.js');
$header->jsFile('../shared2/js/grid.js');
$header->jsFile('../shared2/js/multi_list.js');
$header->jsFile('../shared2/js/popups.js');
$header->jsFile('../shared2/js/page_maker.js');
$header->jsFile('../shared2/js/permissions.js');
$header->jsFile('../shared2/js/swfupload.js');
$header->jsFile('../shared2/js/jquery.swfupload.js');
$header->jsFile('js/Ops.js');
$header->display();

$l_form = new Form('new_db');

$logos = DB::getFiles('settings_files',1,'logo',1);
$logo_img = ($logos) ? 'uploads/'.$logos[0]['name'].'_logo.png' : 'images/logo.png';

echo '
<div class="login_box">
	<div class="login_logo"><img src="'.$logo_img.'" title="Logo" alt="Logo" /></div>
	<div class="logform">';

if (!$l_form->info) {
	$l_form->textInput('new_db','New DB Name');
	$l_form->submitButton('submit','Create');
	$l_form->display();
}
else {
	$db_name = $l_form->info['new_db'];
	if (!$db_name) {
		echo 'No name specified.';
	}
	else {
		$sql = "SHOW DATABASES";
		$result = db_query_array($sql);
		
		if ($result) {
			foreach ($result as $database) {
				if ($database['Database'] == $db_name) {
					$exists = true;
					break;
				}
			}
		}
		
		if ($exists) {
			echo 'Database name exists already.';
		}
		else {
			$sql = "CREATE DATABASE $db_name";
			db_query($sql);
			mysql_select_db ($db_name);
			
			echo 'Database created...';
			flush();
			
			db_query("
			CREATE TABLE IF NOT EXISTS `admin_controls` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `page_id` int(10) unsigned NOT NULL,
			  `tab_id` int(10) unsigned NOT NULL,
			  `action` varchar(50) NOT NULL,
			  `class` varchar(50) DEFAULT NULL,
			  `arguments` text NOT NULL,
			  `order` smallint(3) NOT NULL DEFAULT '0',
			  `is_static` enum('Y','N') NOT NULL DEFAULT 'N',
			  PRIMARY KEY (`id`),
			  KEY `page_id` (`page_id`),
			  KEY `tab_id` (`tab_id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=287");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_controls_methods` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `method` varchar(100) DEFAULT NULL,
			  `arguments` text NOT NULL,
			  `order` smallint(3) NOT NULL DEFAULT '0',
			  `control_id` int(10) unsigned NOT NULL,
			  `p_id` int(10) unsigned NOT NULL,
			  PRIMARY KEY (`id`),
			  KEY `control_id` (`control_id`),
			  KEY `p_id` (`p_id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3507 ;");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_cron` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `method_id` int(10) unsigned NOT NULL,
			  `control_id` int(10) unsigned NOT NULL,
			  `day` varchar(30) NOT NULL,
			  `month` varchar(30) NOT NULL,
			  `year` varchar(30) NOT NULL,
			  `send_condition` varchar(255) NOT NULL,
			  PRIMARY KEY (`id`),
			  KEY `method_id` (`method_id`),
			  KEY `control_id` (`control_id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_groups` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `name` varchar(50) NOT NULL,
			  `order` int(10) unsigned NOT NULL,
			  PRIMARY KEY (`id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=11");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_groups_pages` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `group_id` int(10) unsigned NOT NULL,
			  `page_id` int(10) unsigned NOT NULL,
			  `permission` tinyint(1) unsigned NOT NULL DEFAULT '0',
			  PRIMARY KEY (`id`),
			  KEY `group_id` (`group_id`,`page_id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=122");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_groups_tabs` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `group_id` int(10) unsigned NOT NULL,
			  `tab_id` int(10) unsigned NOT NULL,
			  `permission` tinyint(1) unsigned NOT NULL DEFAULT '0',
			  PRIMARY KEY (`id`),
			  KEY `group_id` (`group_id`,`tab_id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=52");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_image_sizes` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `field_name` varchar(100) NOT NULL,
			  `value` text NOT NULL,
			  PRIMARY KEY (`id`),
			  KEY `field_name` (`field_name`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_order` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `control_id` int(10) unsigned NOT NULL,
			  `user_id` int(10) unsigned NOT NULL,
			  `order_by` varchar(50) NOT NULL,
			  `order_asc` int(10) unsigned NOT NULL,
			  PRIMARY KEY (`id`),
			  KEY `control_id` (`control_id`,`user_id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_pages` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `f_id` int(10) NOT NULL,
			  `name` varchar(255) NOT NULL,
			  `url` varchar(255) NOT NULL,
			  `icon` varchar(255) NOT NULL,
			  `order` smallint(3) unsigned NOT NULL,
			  `page_map_reorders` tinyint(1) NOT NULL,
			  PRIMARY KEY (`id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=58");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_tabs` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `name` varchar(255) NOT NULL,
			  `order` smallint(3) unsigned NOT NULL,
			  `icon` varchar(255) NOT NULL,
			  `url` varchar(255) NOT NULL,
			  `hidden` enum('Y','N') NOT NULL DEFAULT 'N',
			  `is_ctrl_panel` enum('Y','N') NOT NULL DEFAULT 'N',
			  `for_group` int(10) unsigned NOT NULL,
			  PRIMARY KEY (`id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=24");
			
			db_query("CREATE TABLE IF NOT EXISTS `admin_users` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `user` varchar(50) NOT NULL,
			  `pass` varchar(50) NOT NULL,
			  `first_name` varchar(50) NOT NULL,
			  `last_name` varchar(50) NOT NULL,
			  `company` varchar(255) NOT NULL,
			  `address` varchar(255) NOT NULL,
			  `city` varchar(50) NOT NULL,
			  `country_id` int(10) NOT NULL,
			  `phone` varchar(50) NOT NULL,
			  `email` varchar(50) NOT NULL,
			  `website` varchar(255) NOT NULL,
			  `f_id` int(10) unsigned NOT NULL,
			  `order` int(10) unsigned NOT NULL DEFAULT '0',
			  `is_admin` enum('N','Y') NOT NULL DEFAULT 'N',
			  PRIMARY KEY (`id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=28");
			
			db_query("CREATE TABLE IF NOT EXISTS `iso_countries` (
			  `id` int(10) NOT NULL,
			  `country_id` int(10) NOT NULL,
			  `locale` varchar(10) NOT NULL DEFAULT 'en',
			  `code` char(2) NOT NULL,
			  `name` varchar(200) CHARACTER SET utf8 DEFAULT NULL,
			  `prefix` varchar(50) DEFAULT NULL,
			  PRIMARY KEY (`id`)
			) ENGINE=MyISAM DEFAULT CHARSET=latin1");
			
			db_query("CREATE TABLE IF NOT EXISTS `sessions` (
			  `session_id` varchar(32) NOT NULL DEFAULT '',
			  `session_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
			  `session_start` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
			  `session_value` text NOT NULL,
			  `ip_address` varchar(16) NOT NULL DEFAULT '',
			  `user_agent` varchar(255) NOT NULL DEFAULT '',
			  PRIMARY KEY (`session_id`)
			) ENGINE=MyISAM DEFAULT CHARSET=latin1");
			
			db_query("CREATE TABLE IF NOT EXISTS `settings` (
			  `name` varchar(200) NOT NULL DEFAULT '',
			  `value` text NOT NULL,
			  PRIMARY KEY (`name`)
			) ENGINE=MyISAM DEFAULT CHARSET=latin1");
			
			db_query("CREATE TABLE IF NOT EXISTS `settings_files` (
			  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
			  `f_id` int(10) unsigned NOT NULL,
			  `ext` char(4) NOT NULL,
			  `dir` varchar(255) NOT NULL,
			  `url` text NOT NULL,
			  `old_name` varchar(255) NOT NULL,
			  `field_name` varchar(50) NOT NULL,
			  PRIMARY KEY (`id`),
			  KEY `f_id` (`f_id`)
			) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2");
			
			echo 'Tables created...';
			flush();
			
			db_query("INSERT INTO `admin_users` (`id`, `user`, `pass`, `first_name`, `last_name`, `company`, `address`, `city`, `country_id`, `phone`, `email`, `website`, `f_id`, `order`, `is_admin`) VALUES
			(16, 'admin', 'tecnorganica', 'Moises', 'Bassan', '', '', '', 0, '', '', '', 2, 2, 'Y')");
			
			db_query("INSERT INTO `iso_countries` (`id`, `country_id`, `locale`, `code`, `name`, `prefix`) VALUES
			(1, 1, 'en', 'AF', 'Afghanistan', '+93'),
			(2, 2, 'en', 'AL', 'Albania', '+355'),
			(3, 3, 'en', 'DZ', 'Algeria', '+213'),
			(4, 4, 'en', 'AD', 'Andorra', '+376'),
			(5, 5, 'en', 'AO', 'Angola', '+244'),
			(6, 6, 'en', 'AG', 'Antigua and Barbuda', '+1-268'),
			(7, 7, 'en', 'AR', 'Argentina', '+54'),
			(8, 8, 'en', 'AM', 'Armenia', '+374'),
			(9, 9, 'en', 'AU', 'Australia', '+61'),
			(10, 10, 'en', 'AT', 'Austria', '+43'),
			(11, 11, 'en', 'AZ', 'Azerbaijan', '+994'),
			(12, 12, 'en', 'BS', 'Bahamas, The', '+1-242'),
			(13, 13, 'en', 'BH', 'Bahrain', '+973'),
			(14, 14, 'en', 'BD', 'Bangladesh', '+880'),
			(15, 15, 'en', 'BB', 'Barbados', '+1-246'),
			(16, 16, 'en', 'BY', 'Belarus', '+375'),
			(17, 17, 'en', 'BE', 'Belgium', '+32'),
			(18, 18, 'en', 'BZ', 'Belize', '+501'),
			(19, 19, 'en', 'BJ', 'Benin', '+229'),
			(20, 20, 'en', 'BT', 'Bhutan', '+975'),
			(21, 21, 'en', 'BO', 'Bolivia', '+591'),
			(22, 22, 'en', 'BA', 'Bosnia and Herzegovina', '+387'),
			(23, 23, 'en', 'BW', 'Botswana', '+267'),
			(24, 24, 'en', 'BR', 'Brazil', '+55'),
			(25, 25, 'en', 'BN', 'Brunei', '+673'),
			(26, 26, 'en', 'BG', 'Bulgaria', '+359'),
			(27, 27, 'en', 'BF', 'Burkina Faso', '+226'),
			(28, 28, 'en', 'BI', 'Burundi', '+257'),
			(29, 29, 'en', 'KH', 'Cambodia', '+855'),
			(30, 30, 'en', 'CM', 'Cameroon', '+237'),
			(31, 31, 'en', 'CA', 'Canada', '+1'),
			(32, 32, 'en', 'CV', 'Cape Verde', '+238'),
			(33, 33, 'en', 'CF', 'Central African Republic', '+236'),
			(34, 34, 'en', 'TD', 'Chad', '+235'),
			(35, 35, 'en', 'CL', 'Chile', '+56'),
			(36, 36, 'en', 'CN', 'China, People''s Republic of', '+86'),
			(37, 37, 'en', 'CO', 'Colombia', '+57'),
			(38, 38, 'en', 'KM', 'Comoros', '+269'),
			(39, 39, 'en', 'CD', 'Congo, Democratic Republic of the (Congo ? Kinshasa)', '+243'),
			(40, 40, 'en', 'CG', 'Congo, Republic of the (Congo ? Brazzaville)', '+242'),
			(41, 41, 'en', 'CR', 'Costa Rica', '+506'),
			(42, 42, 'en', 'CI', 'Cote d''Ivoire (Ivory Coast)', '+225'),
			(43, 43, 'en', 'HR', 'Croatia', '+385'),
			(44, 44, 'en', 'CU', 'Cuba', '+53'),
			(45, 45, 'en', 'CY', 'Cyprus', '+357'),
			(46, 46, 'en', 'CZ', 'Czech Republic', '+420'),
			(47, 47, 'en', 'DK', 'Denmark', '+45'),
			(48, 48, 'en', 'DJ', 'Djibouti', '+253'),
			(49, 49, 'en', 'DM', 'Dominica', '+1-767'),
			(50, 50, 'en', 'DO', 'Dominican Republic', '+1-809 and 1-829'),
			(51, 51, 'en', 'EC', 'Ecuador', '+593'),
			(52, 52, 'en', 'EG', 'Egypt', '+20'),
			(53, 53, 'en', 'SV', 'El Salvador', '+503'),
			(54, 54, 'en', 'GQ', 'Equatorial Guinea', '+240'),
			(55, 55, 'en', 'ER', 'Eritrea', '+291'),
			(56, 56, 'en', 'EE', 'Estonia', '+372'),
			(57, 57, 'en', 'ET', 'Ethiopia', '+251'),
			(58, 58, 'en', 'FJ', 'Fiji', '+679'),
			(59, 59, 'en', 'FI', 'Finland', '+358'),
			(60, 60, 'en', 'FR', 'France', '+33'),
			(61, 61, 'en', 'GA', 'Gabon', '+241'),
			(62, 62, 'en', 'GM', 'Gambia, The', '+220'),
			(63, 63, 'en', 'GE', 'Georgia', '+995'),
			(64, 64, 'en', 'DE', 'Germany', '+49'),
			(65, 65, 'en', 'GH', 'Ghana', '+233'),
			(66, 66, 'en', 'GR', 'Greece', '+30'),
			(67, 67, 'en', 'GD', 'Grenada', '+1-473'),
			(68, 68, 'en', 'GT', 'Guatemala', '+502'),
			(69, 69, 'en', 'GN', 'Guinea', '+224'),
			(70, 70, 'en', 'GW', 'Guinea-Bissau', '+245'),
			(71, 71, 'en', 'GY', 'Guyana', '+592'),
			(72, 72, 'en', 'HT', 'Haiti', '+509'),
			(73, 73, 'en', 'HN', 'Honduras', '+504'),
			(74, 74, 'en', 'HU', 'Hungary', '+36'),
			(75, 75, 'en', 'IS', 'Iceland', '+354'),
			(76, 76, 'en', 'IN', 'India', '+91'),
			(77, 77, 'en', 'ID', 'Indonesia', '+62'),
			(78, 78, 'en', 'IR', 'Iran', '+98'),
			(79, 79, 'en', 'IQ', 'Iraq', '+964'),
			(80, 80, 'en', 'IE', 'Ireland', '+353'),
			(81, 81, 'en', 'IL', 'Israel', '+972'),
			(82, 82, 'en', 'IT', 'Italy', '+39'),
			(83, 83, 'en', 'JM', 'Jamaica', '+1-876'),
			(84, 84, 'en', 'JP', 'Japan', '+81'),
			(85, 85, 'en', 'JO', 'Jordan', '+962'),
			(86, 86, 'en', 'KZ', 'Kazakhstan', '+7'),
			(87, 87, 'en', 'KE', 'Kenya', '+254'),
			(88, 88, 'en', 'KI', 'Kiribati', '+686'),
			(89, 89, 'en', 'KP', 'Korea, Democratic People''s Republic of (North Korea)', '+850'),
			(90, 90, 'en', 'KR', 'Korea, Republic of  (South Korea)', '+82'),
			(91, 91, 'en', 'KW', 'Kuwait', '+965'),
			(92, 92, 'en', 'KG', 'Kyrgyzstan', '+996'),
			(93, 93, 'en', 'LA', 'Laos', '+856'),
			(94, 94, 'en', 'LV', 'Latvia', '+371'),
			(95, 95, 'en', 'LB', 'Lebanon', '+961'),
			(96, 96, 'en', 'LS', 'Lesotho', '+266'),
			(97, 97, 'en', 'LR', 'Liberia', '+231'),
			(98, 98, 'en', 'LY', 'Libya', '+218'),
			(99, 99, 'en', 'LI', 'Liechtenstein', '+423'),
			(100, 100, 'en', 'LT', 'Lithuania', '+370'),
			(101, 101, 'en', 'LU', 'Luxembourg', '+352'),
			(102, 102, 'en', 'MK', 'Macedonia', '+389'),
			(103, 103, 'en', 'MG', 'Madagascar', '+261'),
			(104, 104, 'en', 'MW', 'Malawi', '+265'),
			(105, 105, 'en', 'MY', 'Malaysia', '+60'),
			(106, 106, 'en', 'MV', 'Maldives', '+960'),
			(107, 107, 'en', 'ML', 'Mali', '+223'),
			(108, 108, 'en', 'MT', 'Malta', '+356'),
			(109, 109, 'en', 'MH', 'Marshall Islands', '+692'),
			(110, 110, 'en', 'MR', 'Mauritania', '+222'),
			(111, 111, 'en', 'MU', 'Mauritius', '+230'),
			(112, 112, 'en', 'MX', 'Mexico', '+52'),
			(113, 113, 'en', 'FM', 'Micronesia', '+691'),
			(114, 114, 'en', 'MD', 'Moldova', '+373'),
			(115, 115, 'en', 'MC', 'Monaco', '+377'),
			(116, 116, 'en', 'MN', 'Mongolia', '+976'),
			(117, 117, 'en', 'ME', 'Montenegro', '+382'),
			(118, 118, 'en', 'MA', 'Morocco', '+212'),
			(119, 119, 'en', 'MZ', 'Mozambique', '+258'),
			(120, 120, 'en', 'MM', 'Myanmar (Burma)', '+95'),
			(121, 121, 'en', 'NA', 'Namibia', '+264'),
			(122, 122, 'en', 'NR', 'Nauru', '+674'),
			(123, 123, 'en', 'NP', 'Nepal', '+977'),
			(124, 124, 'en', 'NL', 'Netherlands', '+31'),
			(125, 125, 'en', 'NZ', 'New Zealand', '+64'),
			(126, 126, 'en', 'NI', 'Nicaragua', '+505'),
			(127, 127, 'en', 'NE', 'Niger', '+227'),
			(128, 128, 'en', 'NG', 'Nigeria', '+234'),
			(129, 129, 'en', 'NO', 'Norway', '+47'),
			(130, 130, 'en', 'OM', 'Oman', '+968'),
			(131, 131, 'en', 'PK', 'Pakistan', '+92'),
			(132, 132, 'en', 'PW', 'Palau', '+680'),
			(133, 133, 'en', 'PA', 'Panama', '+507'),
			(134, 134, 'en', 'PG', 'Papua New Guinea', '+675'),
			(135, 135, 'en', 'PY', 'Paraguay', '+595'),
			(136, 136, 'en', 'PE', 'Peru', '+51'),
			(137, 137, 'en', 'PH', 'Philippines', '+63'),
			(138, 138, 'en', 'PL', 'Poland', '+48'),
			(139, 139, 'en', 'PT', 'Portugal', '+351'),
			(140, 140, 'en', 'QA', 'Qatar', '+974'),
			(141, 141, 'en', 'RO', 'Romania', '+40'),
			(142, 142, 'en', 'RU', 'Russia', '+7'),
			(143, 143, 'en', 'RW', 'Rwanda', '+250'),
			(144, 144, 'en', 'KN', 'Saint Kitts and Nevis', '+1-869'),
			(145, 145, 'en', 'LC', 'Saint Lucia', '+1-758'),
			(146, 146, 'en', 'VC', 'Saint Vincent and the Grenadines', '+1-784'),
			(147, 147, 'en', 'WS', 'Samoa', '+685'),
			(148, 148, 'en', 'SM', 'San Marino', '+378'),
			(149, 149, 'en', 'ST', 'Sao Tome and Principe', '+239'),
			(150, 150, 'en', 'SA', 'Saudi Arabia', '+966'),
			(151, 151, 'en', 'SN', 'Senegal', '+221'),
			(152, 152, 'en', 'RS', 'Serbia', '+381'),
			(153, 153, 'en', 'SC', 'Seychelles', '+248'),
			(154, 154, 'en', 'SL', 'Sierra Leone', '+232'),
			(155, 155, 'en', 'SG', 'Singapore', '+65'),
			(156, 156, 'en', 'SK', 'Slovakia', '+421'),
			(157, 157, 'en', 'SI', 'Slovenia', '+386'),
			(158, 158, 'en', 'SB', 'Solomon Islands', '+677'),
			(159, 159, 'en', 'SO', 'Somalia', '+252'),
			(160, 160, 'en', 'ZA', 'South Africa', '+27'),
			(161, 161, 'en', 'ES', 'Spain', '+34'),
			(162, 162, 'en', 'LK', 'Sri Lanka', '+94'),
			(163, 163, 'en', 'SD', 'Sudan', '+249'),
			(164, 164, 'en', 'SR', 'Suriname', '+597'),
			(165, 165, 'en', 'SZ', 'Swaziland', '+268'),
			(166, 166, 'en', 'SE', 'Sweden', '+46'),
			(167, 167, 'en', 'CH', 'Switzerland', '+41'),
			(168, 168, 'en', 'SY', 'Syria', '+963'),
			(169, 169, 'en', 'TJ', 'Tajikistan', '+992'),
			(170, 170, 'en', 'TZ', 'Tanzania', '+255'),
			(171, 171, 'en', 'TH', 'Thailand', '+66'),
			(172, 172, 'en', 'TL', 'Timor-Leste (East Timor)', '+670'),
			(173, 173, 'en', 'TG', 'Togo', '+228'),
			(174, 174, 'en', 'TO', 'Tonga', '+676'),
			(175, 175, 'en', 'TT', 'Trinidad and Tobago', '+1-868'),
			(176, 176, 'en', 'TN', 'Tunisia', '+216'),
			(177, 177, 'en', 'TR', 'Turkey', '+90'),
			(178, 178, 'en', 'TM', 'Turkmenistan', '+993'),
			(179, 179, 'en', 'TV', 'Tuvalu', '+688'),
			(180, 180, 'en', 'UG', 'Uganda', '+256'),
			(181, 181, 'en', 'UA', 'Ukraine', '+380'),
			(182, 182, 'en', 'AE', 'United Arab Emirates', '+971'),
			(183, 183, 'en', 'GB', 'United Kingdom', '+44'),
			(184, 184, 'en', 'US', 'United States', '+1'),
			(185, 185, 'en', 'UY', 'Uruguay', '+598'),
			(186, 186, 'en', 'UZ', 'Uzbekistan', '+998'),
			(187, 187, 'en', 'VU', 'Vanuatu', '+678'),
			(188, 188, 'en', 'VA', 'Vatican City', '+379'),
			(189, 189, 'en', 'VE', 'Venezuela', '+58'),
			(190, 190, 'en', 'VN', 'Viet Nam', '+84'),
			(191, 191, 'en', 'YE', 'Yemen', '+967'),
			(192, 192, 'en', 'ZM', 'Zambia', '+260'),
			(193, 193, 'en', 'ZW', 'Zimbabwe', '+263'),
			(194, 194, 'en', 'GE', 'Abkhazia', '+995'),
			(195, 195, 'en', 'TW', 'China, Republic of (Taiwan)', '+886'),
			(196, 196, 'en', 'AZ', 'Nagorno-Karabakh', '+374-97'),
			(197, 197, 'en', 'CY', 'Northern Cyprus', '+90-392'),
			(198, 198, 'en', 'MD', 'Pridnestrovie (Transnistria)', '+373-533'),
			(199, 199, 'en', 'SO', 'Somaliland', '+252'),
			(200, 200, 'en', 'GE', 'South Ossetia', '+995'),
			(201, 201, 'en', 'AU', 'Ashmore and Cartier Islands', ''),
			(202, 202, 'en', 'CX', 'Christmas Island', '+61'),
			(203, 203, 'en', 'CC', 'Cocos (Keeling) Islands', '+61'),
			(204, 204, 'en', 'AU', 'Coral Sea Islands', ''),
			(205, 205, 'en', 'HM', 'Heard Island and McDonald Islands', ''),
			(206, 206, 'en', 'NF', 'Norfolk Island', '+672'),
			(207, 207, 'en', 'NC', 'New Caledonia', '+687'),
			(208, 208, 'en', 'PF', 'French Polynesia', '+689'),
			(209, 209, 'en', 'YT', 'Mayotte', '+269'),
			(210, 210, 'en', 'PM', 'Saint Pierre and Miquelon', '+508'),
			(211, 211, 'en', 'WF', 'Wallis and Futuna', '+681'),
			(212, 212, 'en', 'TF', 'French Southern and Antarctic Lands', ''),
			(213, 213, 'en', 'PF', 'Clipperton Island', ''),
			(214, 214, 'en', '', 'French Scattered Islands in the Indian Ocean', ''),
			(215, 215, 'en', 'BV', 'Bouvet Island', ''),
			(216, 216, 'en', 'CK', 'Cook Islands', '+682'),
			(217, 217, 'en', 'NU', 'Niue', '+683'),
			(218, 218, 'en', 'TK', 'Tokelau', '+690'),
			(219, 219, 'en', 'GG', 'Guernsey', '+44'),
			(220, 220, 'en', 'IM', 'Isle of Man', '+44'),
			(221, 221, 'en', 'JE', 'Jersey', '+44'),
			(222, 222, 'en', 'AI', 'Anguilla', '+1-264'),
			(223, 223, 'en', 'BM', 'Bermuda', '+1-441'),
			(224, 224, 'en', 'IO', 'British Indian Ocean Territory', '+246'),
			(225, 225, 'en', '', 'British Sovereign Base Areas', '+357'),
			(226, 226, 'en', 'VG', 'British Virgin Islands', '+1-284'),
			(227, 227, 'en', 'KY', 'Cayman Islands', '+1-345'),
			(228, 228, 'en', 'FK', 'Falkland Islands (Islas Malvinas)', '+500'),
			(229, 229, 'en', 'GI', 'Gibraltar', '+350'),
			(230, 230, 'en', 'MS', 'Montserrat', '+1-664'),
			(231, 231, 'en', 'PN', 'Pitcairn Islands', ''),
			(232, 232, 'en', 'SH', 'Saint Helena', '+290'),
			(233, 233, 'en', 'GS', 'South Georgia and the South Sandwich Islands', ''),
			(234, 234, 'en', 'TC', 'Turks and Caicos Islands', '+1-649'),
			(235, 235, 'en', 'MP', 'Northern Mariana Islands', '+1-670'),
			(236, 236, 'en', 'PR', 'Puerto Rico', '+1-787 and 1-939'),
			(237, 237, 'en', 'AS', 'American Samoa', '+1-684'),
			(238, 238, 'en', 'UM', 'Baker Island', ''),
			(239, 239, 'en', 'GU', 'Guam', '+1-671'),
			(240, 240, 'en', 'UM', 'Howland Island', ''),
			(241, 241, 'en', 'UM', 'Jarvis Island', ''),
			(242, 242, 'en', 'UM', 'Johnston Atoll', ''),
			(243, 243, 'en', 'UM', 'Kingman Reef', ''),
			(244, 244, 'en', 'UM', 'Midway Islands', ''),
			(245, 245, 'en', 'UM', 'Navassa Island', ''),
			(246, 246, 'en', 'UM', 'Palmyra Atoll', ''),
			(247, 247, 'en', 'VI', 'U.S. Virgin Islands', '+1-340'),
			(248, 248, 'en', 'UM', 'Wake Island', ''),
			(249, 249, 'en', 'HK', 'Hong Kong', '+852'),
			(250, 250, 'en', 'MO', 'Macau', '+853'),
			(251, 251, 'en', 'FO', 'Faroe Islands', '+298'),
			(252, 252, 'en', 'GL', 'Greenland', '+299'),
			(253, 253, 'en', 'GF', 'French Guiana', '+594'),
			(254, 254, 'en', 'GP', 'Guadeloupe', '+590'),
			(255, 255, 'en', 'MQ', 'Martinique', '+596'),
			(256, 256, 'en', 'RE', 'Reunion', '+262'),
			(257, 257, 'en', 'AX', 'Aland', '+358-18'),
			(258, 258, 'en', 'AW', 'Aruba', '+297'),
			(259, 259, 'en', 'AN', 'Netherlands Antilles', '+599'),
			(260, 260, 'en', 'SJ', 'Svalbard', '+47'),
			(261, 261, 'en', 'AC', 'Ascension', '+247'),
			(262, 262, 'en', 'TA', 'Tristan da Cunha', ''),
			(263, 263, 'en', 'AQ', 'Antarctica', ''),
			(264, 264, 'en', 'CS', 'Kosovo', '+381'),
			(265, 265, 'en', 'PS', 'Palestinian Territories (Gaza Strip and West Bank)', '+970'),
			(266, 266, 'en', 'EH', 'Western Sahara', '+212'),
			(267, 267, 'en', 'AQ', 'Australian Antarctic Territory', ''),
			(268, 268, 'en', 'AQ', 'Ross Dependency', ''),
			(269, 269, 'en', 'AQ', 'Peter I Island', ''),
			(270, 270, 'en', 'AQ', 'Queen Maud Land', ''),
			(271, 271, 'en', 'AQ', 'British Antarctic Territory', '')");
			
			db_query("INSERT INTO `settings` (`name`, `value`) VALUES
			('pass_regex', '/[a-zA-Z0-9]{4,}/'),
			('verify_default_error', '[field] es un campo requerido.'),
			('verify_email_error', 'Debe ingresar un email v&Atilde;&iexcl;lido.'),
			('verify_phone_error', 'You must enter a valid phone number.'),
			('verify_file_type_error', 'Wrong file type.'),
			('verify_file_size_error', 'Wrong file size.'),
			('verify_file_misc_error', 'Error subiendo archivo.'),
			('verify_file_required_error', 'Debe ingresar un archivo.'),
			('verify_password_error', 'Su contrase&Atilde;&plusmn;a debe tener por lo menos 4 car&Atilde;&iexcl;cteres.'),
			('verify_zip_error', 'You must enter a valid zip code.'),
			('verify_date_error', '[field] must be in the valid range of dates.'),
			('verify_custom_error', 'Entrada inv&Atilde;&iexcl;lida para [field].'),
			('verify_cat_select_error', 'Deber&Atilde;&iexcl; seleccionar al menos [n] categor&Atilde;&shy;as.'),
			('verify_error_class', 'error'),
			('req_img', '&lt;em&gt;*&lt;/em&gt;'),
			('table_creation_error', 'No se pudo crear la tabla.'),
			('form_get_record_error', 'No se pudo cargar el record.'),
			('form_save_error', 'No se pudo guardar la informaci&Atilde;&sup3;n.'),
			('form_update_error', 'No se pudo actualizar la informaci&Atilde;&sup3;n.'),
			('file_save_error', 'El archivo no se pudo guardar.'),
			('alt_url_label', ' or url '),
			('table_created', 'Successfully created database table.'),
			('form_save_message', 'Formulario guardado exit&Atilde;&sup3;samente.'),
			('form_update_message', 'Record [field] actualizado.'),
			('file_save_message', 'Campo [field] guardado.'),
			('temp_file_location', 'tempfiles/'),
			('default_upload_location', 'uploads/'),
			('accepted_file_formats', ''),
			('accepted_image_formats', 'a:4:{i:1;s:4:&quot;jpeg&quot;;i:2;s:3:&quot;gif&quot;;i:3;s:3:&quot;png&quot;;i:4;s:3:&quot;jpg&quot;;}'),
			('accepted_audio_formats', 'a:2:{i:1;s:3:&quot;mp3&quot;;i:2;s:3:&quot;wma&quot;;}'),
			('image_sizes', 'a:3:{s:5:&quot;small&quot;;a:2:{s:6:&quot;height&quot;;s:2:&quot;50&quot;;s:5:&quot;width&quot;;s:2:&quot;50&quot;;}s:6:&quot;medium&quot;;a:2:{s:6:&quot;height&quot;;s:3:&quot;275&quot;;s:5:&quot;width&quot;;s:3:&quot;200&quot;;}s:5:&quot;large&quot;;a:2:{s:6:&quot;height&quot;;s:4:&quot;1375&quot;;s:5:&quot;width&quot;;s:4:&quot;1000&quot;;}}'),
			('ajax_confirm_delete', 'Seguro que desea borrar esto?'),
			('pm_copy_wrong_class', 'No se puede pegar. El m&Atilde;&copy;todo es para otra clase.'),
			('pmt_record_files', 'Record: Show Uploaded Files'),
			('subtotal_label', 'Total P&Atilde;&iexcl;g.'),
			('subavg_label', 'Promedio P&Atilde;&iexcl;g.'),
			('total_label', 'Gran Total'),
			('avg_label', 'Gran Promedio'),
			('pmt_grid_aggregate', 'Grid: Aggregate Field'),
			('date_picker_icon', '../shared/images/date_picker.gif'),
			('date_picker_css', '../shared/css/date_picker.css'),
			('default_date_format', 'j-n-Y'),
			('placeholder_image', 'images/placeholder.gif'),
			('gallery_left_arrow', '&lt;'),
			('gallery_right_arrow', '&gt;'),
			('grid_no_table_error', 'La table [field] no existe.'),
			('grid_no_field_error', 'El campo [field] no existe.'),
			('grid_no_results', 'No hay resultados para mostrar.'),
			('pagination_label', 'Mostrando [results] resultados en [num_pages] p&Atilde;&iexcl;ginas.'),
			('pmt_grid_tokenizer', 'Grid: Tokenizer Filter'),
			('pmt_calendar_autocomplete', 'Calendar: Autocomplete Filter'),
			('pmt_calendar_tokenizer', 'Calendar: Tokenizer Filter'),
			('pmt_calendar_checkbox', 'Calendar: Checkbox Filter'),
			('pmt_calendar_select', 'Calendar: Select Filter'),
			('print_icon', '&lt;img src=&quot;css/basic/print.png&quot;&gt;'),
			('pm_decouple_cancel', 'Y'),
			('pm_cancel_back', 'Y'),
			('pmt_form_cancel_button', 'Form: Cancel Button'),
			('pmt_record_cancel_button', 'Record: Cancel Button'),
			('pmt_record_button', 'Record: Button'),
			('pmt_form_file_multiple', 'Form: File Input (Multiple)'),
			('my_account_button', 'Mi Cuenta'),
			('edit_tabs_this_button', 'Editar Esta P&Atilde;&iexcl;gina'),
			('path_ctrl', 'Panel de Control'),
			('back', 'Atr&Atilde;&iexcl;s'),
			('forward', 'Adelante'),
			('up_directory', 'Subir un directorio'),
			('add_directory', 'Agregar nuevo directorio'),
			('add_step', 'Agregar nuevo paso'),
			('download_results', 'Descargar Resultados'),
			('download_all', 'Descargar Todos los Archivos'),
			('save_order', 'Guardar Orden'),
			('user_unique_error', '[field] debe tener un valor &Atilde;&ordm;nico.'),
			('user_username', 'Usuario'),
			('user_password', 'Contrase&Atilde;&plusmn;a'),
			('user_last_name', 'Apellido'),
			('user_phone', 'Tel.'),
			('user_email', 'Email'),
			('user_group', 'Grupo'),
			('user_group_name', 'Nombre'),
			('user_is_admin', 'Es Administrador?'),
			('comments_action_2_short', 'edit&Atilde;&sup3; el record.'),
			('comments_action_3_short', 'cre&Atilde;&sup3; el record.'),
			('comments_action_4_short', 'mando el record al paso &lt;b&gt;[documentos.paso_id,pasos.step_order,pasos.name]&lt;/b&gt;'),
			('comments_action_5_short', ''),
			('pmt_grid_label', 'Grid: Label'),
			('pmt_filemanager', 'File Manager Control'),
			('pmt_filemanager_add_table', 'File Manager: Add Table'),
			('pmt_redirect', 'Redirect Control'),
			('pmt_flowchart', 'Flow Chart Control'),
			('user_first_name', 'Nombre'),
			('path_attributes', 'Atributos'),
			('path_message', 'Mensaje'),
			('path_error', 'Error'),
			('path_prompt', 'Confirmar'),
			('first_page_text', '&lt; Primero'),
			('last_page_text', '&Atilde;šltimo &gt;'),
			('results_per_page_text', 'Resultados por p&Atilde;&iexcl;gina: '),
			('search_text', 'Buscar:'),
			('filter_submit_text', 'Filtrar'),
			('rows_per_page', '30'),
			('move_hover_caption', 'Mover'),
			('view_hover_caption', 'Ver'),
			('save_caption', 'Guardar Cambios'),
			('email_send_error', 'No se pudo mandar el email.'),
			('save_button', 'Guardar Cambios'),
			('save_icon', '&lt;img src=&quot;css/basic/save.png&quot;&gt;'),
			('delete_hover_caption', 'Borrar'),
			('home_icon', '&lt;img title=&quot;Home&quot; src=&quot;css/organic/home.png&quot; /&gt;'),
			('dragdrop_add_child_button', 'Agregar Sub'),
			('edit_tabs_button', 'Editar P&Atilde;&iexcl;ginas'),
			('edit_page_button', '&lt;img title=&quot;Configure&quot; src=&quot;css/organic/configure.png&quot; /&gt;'),
			('x_button', 'x'),
			('ok_button', 'OK'),
			('cancel_button', 'Cancelar'),
			('logout_button', 'Cerrar Sesion'),
			('path_separator', ' / '),
			('path_edit_tabs', 'Pages and Tabs'),
			('path_edit', 'Editar'),
			('path_view', 'Ver'),
			('path_users', 'Grupos y Usuarios'),
			('path_settings', 'Configuracion'),
			('ajax_save_message', 'La informaci&Atilde;&sup3;n fu&Atilde;&copy; actualizada.'),
			('ajax_save_error', 'La informaci&Atilde;&sup3;n no se pudo actualizar.'),
			('ajax_insert_error', 'No se pudo crear el record nuevo.'),
			('ajax_delete_error', 'El record no pudo ser borrado.'),
			('login_empty_user', 'Debe ingresar un nombre de usuario.'),
			('login_empty_pass', 'Debe ingresar una contrase&Atilde;&plusmn;a.'),
			('login_invalid', 'Login inv&Atilde;&iexcl;lido.'),
			('no_database_error', 'No hay base de datos.'),
			('pm_list_tab', 'List'),
			('pm_form_tab', 'Form'),
			('pm_record_tab', 'Record'),
			('pmt_list', 'List Control'),
			('pmt_list_add_table', 'List: Add Table'),
			('pmt_grid', 'Grid Control'),
			('pmt_grid_field', 'Grid: Field'),
			('pmt_grid_autocomplete', 'Grid: Autocomplete Filter'),
			('pmt_grid_cats', 'Grid: Categories Filter'),
			('pmt_grid_checkbox', 'Grid: Checkbox Filter'),
			('pmt_grid_date_end', 'Grid: EndDate Filter'),
			('pmt_grid_date_start', 'Grid: StartDate Filter'),
			('pmt_grid_first_letter', 'Grid: FirstLetter Filter'),
			('pmt_grid_per_page', 'Grid: ResultsPerPage Filter'),
			('pmt_grid_radio', 'Grid: Radio Filter'),
			('pmt_grid_search', 'Grid: Search Filter'),
			('pmt_grid_select', 'Grid: Select Filter'),
			('pmt_form', 'Form Control'),
			('pmt_form_text_input', 'Form: Text Input'),
			('pmt_form_text_editor', 'Form: Text Editor'),
			('pmt_form_text_area', 'Form: Text Area'),
			('pmt_form_auto_complete', 'Form: Autocomplete'),
			('pmt_form_button', 'Form: Button'),
			('pmt_form_cat_select', 'Form: Category Select'),
			('pmt_form_checkbox', 'Form: Checkbox'),
			('pmt_form_date_widget', 'Form: Date Input'),
			('pmt_form_end_fieldset', 'Form: End Fieldset'),
			('pmt_form_end_group', 'Form: End Group'),
			('pmt_form_file_input', 'Form: File Input'),
			('pmt_form_gallery', 'Form: Gallery'),
			('pmt_form_hidden_input', 'Form: Hidden Input'),
			('pmt_form_password_input', 'Form: Password Input'),
			('pmt_form_radio_input', 'Form: Radio Input'),
			('pmt_form_reset_button', 'Form: Reset Button'),
			('pmt_form_select_input', 'Form: Select Input'),
			('pmt_form_start_fieldset', 'Form: Start Fieldset'),
			('pmt_form_start_group', 'Form: Start Group'),
			('pmt_form_submit_button', 'Form: Submit Button'),
			('pmt_record', 'Record Control'),
			('pmt_record_end_table', 'Record: End Table'),
			('pmt_record_field', 'Record: Add Field'),
			('pmt_record_gallery', 'Record: Gallery'),
			('pmt_record_heading', 'Record: Heading'),
			('pmt_record_image', 'Record: Image'),
			('pmt_record_start_table', 'Record: Sutable'),
			('pmt_gallery_image', 'Gallery: Image'),
			('pmt_gallery_multiple', 'Gallery: Multiple'),
			('pmt_tabs', 'Tabs Control'),
			('pmt_tabs_make_tab', 'Tabs: Add Tab'),
			('auto_create_table', 'Y'),
			('file_icons', ''),
			('add_new_caption', 'Crear Nuevo'),
			('print_caption', 'Imprimir'),
			('edit_hover_caption', 'Editar'),
			('skin', 'black_blue'),
			('logo', 'css/basic/logo.png'),
			('verify_invalid_char_error', 'Car&Atilde;&iexcl;cter inv&Atilde;&iexcl;lido para [field].'),
			('capcha_error', ''),
			('compare_error', 'La contrase&Atilde;&plusmn;a debe ser igual que la verificaci&Atilde;&sup3;n.'),
			('value_exists_error', 'El nombre de usuario que ha seleccionado ya est&Atilde;&iexcl; en uso.'),
			('default_timezone', 'America/Caracas'),
			('up', '&lt;img src=&quot;css/organic/up.gif&quot;&gt;'),
			('down', '&lt;img src=&quot;css/organic/down.gif&quot;&gt;'),
			('grid_activate_button', 'Activar'),
			('grid_deactivate_button', 'Desactivar'),
			('invalid_email_error', 'Email inv&Atilde;&iexcl;lido.'),
			('email_sent_message', 'El email de notificaci&Atilde;&sup3;n se mand&Atilde;&sup3; exit&Atilde;&sup3;samente.'),
			('pmt_form_passive_field', 'Form: Passive Field'),
			('pmt_form_colorpicker', 'Form: Color Picker'),
			('pmt_form_colorpicker_nametext', 'Nombre del color...'),
			('pmt_form_multiple', 'Form: Multiple'),
			('delete_button_label', 'Borrar Selecci&Atilde;&sup3;n'),
			('form_email', 'vietpa@tecnorganica.com'),
			('form_email_from', 'Sisven - Sistema Interno'),
			('pmt_form_email_notify', 'Form: Email Notify'),
			('pmt_form_start_area', 'Form: Start Area'),
			('pmt_form_end_area', 'Form: End Area'),
			('pmt_grid_month', 'Grid: Month Filter'),
			('pmt_grid_year', 'Grid: Year Filter'),
			('switch_to_graph', 'Ver Gr&Atilde;&iexcl;fica de Barra'),
			('switch_to_grid', '&lt;img src=&quot;css/organic/table.png&quot;&gt;'),
			('switch_to_list', 'Ver Lista'),
			('switch_to_table', 'Ver Tabla'),
			('name_column_label', 'clasificado por'),
			('value_column_label', 'Mostrar'),
			('combine_label', 'No Clasificar'),
			('switch_to_graph_line', 'Ver Gr&Atilde;&iexcl;fica Lineal'),
			('x_axis', 'sobre'),
			('switch_to_graph_pie', 'Ver Gr&Atilde;&iexcl;fica de Torta'),
			('pmt_form_create_record', 'Form: Create Record'),
			('file_input_button', 'Revisar &gt;'),
			('pmt_form_grid', 'Form: Input Grid'),
			('pmt_record_grid', 'Record: Inline Grid'),
			('pmt_comments', 'Comments Control'),
			('pmt_comments_setparams', 'Comments: Set Parameters'),
			('comments_sent_message', 'Comentario enviado.'),
			('comments_there_are', 'Hay [field] comentarios.'),
			('comments_expand', 'Expandir.'),
			('comments_hide', 'Ocultar.'),
			('comments_none', 'No hay comentarios.'),
			('comments_be_first', 'Pulse aqu&Atilde;&shy; para a&Atilde;&plusmn;adir uno.'),
			('comments_no_url_error', 'No URL in submitted for comments.'),
			('comments_no_record_error', 'No Record submitted for comments.'),
			('comments_less_than_minute', 'hace menos de un minuto.'),
			('comments_minutes_ago', 'hace [field] minutos'),
			('comments_hours_ago', 'hace [field] horas'),
			('comments_days_ago', 'hace [field] d&Atilde;&shy;as'),
			('comments_months_ago', 'hace [field] meses'),
			('comments_wrote_label', 'escribi&Atilde;&sup3;:'),
			('comments_reply_label', 'Responder'),
			('comments_name_label', 'Nombre'),
			('comments_email_label', 'Email'),
			('comments_website_label', 'Sitio Web'),
			('comments_comments_label', 'Comentarios'),
			('comments_submit', 'Enviar'),
			('comment_type_1', '&lt;img src=&quot;css/basic/comment.png&quot;&gt;'),
			('comment_type_2', '&lt;img src=&quot;css/basic/edit_page.png&quot;&gt;'),
			('comment_type_3', '&lt;img src=&quot;css/basic/add_page.png&quot;&gt;'),
			('comment_type_4', '&lt;img src=&quot;css/basic/step_small.png&quot;&gt;'),
			('comment_type_5', ''),
			('comments_action_2', 'edit&Atilde;&sup3; los siguientes campos:'),
			('comments_action_3', 'cre&Atilde;&sup3; el record:'),
			('comments_action_4', 'mando el record al paso &lt;b&gt;[documentos.paso_id,pasos.step_order,pasos.name]&lt;/b&gt;'),
			('comments_action_5', ''),
			('comments_set_to', ''),
			('comments_show_details', 'Mostrar detalles.'),
			('comments_hide_details', 'Ocultar detalles.'),
			('default_time_format', 'g:i a'),
			('cal_week_from', 'Semana desde'),
			('cal_week_until', 'hasta'),
			('cal_today', 'Hoy'),
			('cal_sun', 'Dom'),
			('cal_mon', 'Lun'),
			('cal_tue', 'Mar'),
			('cal_wed', 'Mie'),
			('cal_thur', 'Jue'),
			('cal_fri', 'Vie'),
			('cal_sat', 'Sab'),
			('pmt_calendar', 'Calendar Control'),
			('pmt_calendar_add_table', 'Calendar: Add Table'),
			('pmt_calendar_field', 'Calendar: Add Field'),
			('pmt_calendar_placeholder', 'Calendar: Placeholder Text'),
			('locale', 'spanish'),
			('pmt_page_map', 'Page Map Control'),
			('pagemap_nothing', 'No hay p&Atilde;&iexcl;ginas en esta secci&Atilde;&sup3;n.'),
			('pmt_form_link', 'Form: Link'),
			('pmt_record_link', 'Record: Link'),
			('pm_ctrl_tab', 'Control Panel'),
			('fck_css_file', ''),
			('pmt_form_start_restricted', 'Form: Start Restricted'),
			('pmt_form_end_restricted', 'Form: End Restricted'),
			('pmt_form_aggregate', 'Form: Aggregate Value'),
			('pmt_record_aggregate', 'Record: Aggregate Value'),
			('pmt_form_indicator', 'Form: Indicator'),
			('pmt_record_indicator', 'Record: Indicator'),
			('pmt_grid_inline_form', 'Grid: Inline Form'),
			('pmt_form_edit_record', 'Form: Edit Record'),
			('gallery_desc_icon', 'css/basic/info.png'),
			('gallery_desc_label', 'Descripci&Atilde;&sup3;n del archivo'),
			('gallery_desc_tooltip', 'Haz click para agregar una descripci&Atilde;&sup3;n.'),
			('pmt_page_map_start_area', 'Page Map: Start Area'),
			('pmt_page_map_end_area', 'Page Map: End Area'),
			('print_button', 'Imprimir'),
			('grid_delete_multiple', 'Borrar los elementos seleccionados?'),
			('grid_change', 'Aplicar cambios a los elementos seleccionados?'),
			('ajax_confirm_delete_sub', 'Esto borrar&Atilde;&iexcl; cualquier sub-elemento. Desea continuar?'),
			('pmt_form_include_page', 'Form: Include Page'),
			('pmt_record_include_page', 'Record: Include Page'),
			('ajax_synch', 'Esta seguro que qui'),
			('pmt_synch', 'Synch With Form'),
			('edit_button', '&lt;img title=&quot;Edit&quot; src=&quot;css/basic/edit.png&quot; /&gt;'),
			('pm_exit', 'Salir del editor'),
			('faux_no_options', 'No hay opciones.'),
			('faux_editor_caption', 'P&Atilde;&iexcl;gina actual'),
			('grid_default_reset', 'Borrar Valores'),
			('view_button', ''),
			('move_button', ''),
			('add_new_label', ''),
			('add_new_button', ''),
			('delete_button', ''),
			('dragdrop_enabled_button', ''),
			('dragdrop_disabled_button', ''),
			('admin_button', 'Administrar'),
			('messages_yes_button', '[messages] mensajes nuevos'),
			('messages_no_button', 'No hay mensajes nuevos'),
			('home_label', 'Inicio'),
			('excel_add_new', ''),
			('excel_table_label', ''),
			('excel_upload_file_label', ''),
			('excel_photos_label', ''),
			('excel_next_label', ''),
			('excel_records_updated_label', ''),
			('excel_photos_updated_label', ''),
			('excel_upload_date_label', ''),
			('excel_user_label', ''),
			('pmt_excel', 'Excel Uploader'),
			('excel_invalid_file', ''),
			('excel_invalid_table', ''),
			('grid_until_label', 'hasta'),
			('excel_template', ''),
			('excel_upload_success_label', ''),
			('excel_step1', ''),
			('excel_step2', ''),
			('excel_ignore_label', ''),
			('excel_primary_label', ''),
			('excel_photo_index_label', ''),
			('excel_ignore_first_label', ''),
			('excel_delete_all_label', ''),
			('excel_update_label', ''),
			('excel_auto_activate_label', ''),
			('excel_template_label', ''),
			('excel_update_message', ''),
			('excel_not_update_message', ''),
			('excel_no_primary_error', ''),
			('excel_no_photo_index_error', ''),
			('grid_view_filters', 'Ver Filtros'),
			('grid_hide_filters', 'Esconder Filtros'),
			('grid_click_to_select', ''),
			('grid_n_selected', ''),
			('pmt_form_start_tab', 'Form: Start Tab'),
			('pmt_form_end_tab', 'Form: End Tab'),
			('pmt_form_print_button', 'Form: Print Button');");
			
			echo 'Tables populated...';
			flush();
			
			setcookie("db", $db_name,time()+2592000);
			setcookie("user",'root',time()+2592000);
			setcookie("pass",'',time()+2592000);
			
			echo 'Redirecting...';
			flush();
			
			echo '
			<script type="text/javascript">
				setTimeout(function() {
					ajaxGetPage(\'index.php\');
				},400);
			</script>';
		}
	}
}

echo '</div><div class="clear"></div></div>';
?>